#:schema node_modules/wrangler/config-schema.json
name = "expense-tracker"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-11-13"


[observability]
enabled = true
